---
galaxy_info:
  author: Miguel Alpañez
  description: Base system configuration for DevContainer
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
    - name: Ubuntu
      versions:
        - noble
        - jammy

  galaxy_tags:
    - devcontainer
    - development
    - vscode

dependencies: []
