---
# Funding options for this project
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [malpanez]
# patreon: malpanez
# ko_fi: malpanez
# custom: ["https://www.paypal.me/malpanez"]
