---
# GitHub Labels Configuration
# Sync with: https://github.com/marketplace/actions/github-labeler

# Type labels
- name: 'bug'
  color: 'd73a4a'
  description: 'Something isn''t working'

- name: 'enhancement'
  color: 'a2eeef'
  description: 'New feature or request'

- name: 'documentation'
  color: '0075ca'
  description: 'Improvements or additions to documentation'

- name: 'question'
  color: 'd876e3'
  description: 'Further information is requested'

# Priority labels
- name: 'priority: critical'
  color: 'b60205'
  description: 'Needs immediate attention'

- name: 'priority: high'
  color: 'd93f0b'
  description: 'High priority'

- name: 'priority: medium'
  color: 'fbca04'
  description: 'Medium priority'

- name: 'priority: low'
  color: '0e8a16'
  description: 'Low priority'

# Status labels
- name: 'status: blocked'
  color: 'e99695'
  description: 'Blocked by other issues or external factors'

- name: 'status: in progress'
  color: 'c5def5'
  description: 'Work in progress'

- name: 'status: needs review'
  color: 'fef2c0'
  description: 'Awaiting review'

- name: 'status: wontfix'
  color: 'ffffff'
  description: 'This will not be worked on'

# Stack labels
- name: 'stack: ansible'
  color: 'ee0000'
  description: 'Related to Ansible devcontainer'

- name: 'stack: terraform'
  color: '7b42bc'
  description: 'Related to Terraform devcontainer'

- name: 'stack: golang'
  color: '00add8'
  description: 'Related to Golang devcontainer'

- name: 'stack: latex'
  color: '008080'
  description: 'Related to LaTeX devcontainer'

- name: 'stack: all'
  color: '5319e7'
  description: 'Affects all devcontainer stacks'

# Area labels
- name: 'area: ci/cd'
  color: 'bfdadc'
  description: 'CI/CD workflows and automation'

- name: 'area: dockerfile'
  color: '0052cc'
  description: 'Dockerfile or container build issues'

- name: 'area: security'
  color: 'b60205'
  description: 'Security related'

- name: 'area: performance'
  color: 'fef2c0'
  description: 'Performance improvements'

- name: 'area: dependencies'
  color: '0366d6'
  description: 'Dependency updates'

# Special labels
- name: 'good first issue'
  color: '7057ff'
  description: 'Good for newcomers'

- name: 'help wanted'
  color: '008672'
  description: 'Extra attention is needed'

- name: 'invalid'
  color: 'e4e669'
  description: 'This doesn''t seem right'

- name: 'duplicate'
  color: 'cfd3d7'
  description: 'This issue or pull request already exists'

- name: 'stale'
  color: 'fef2c0'
  description: 'Inactive for extended period'

- name: 'dependencies'
  color: '0366d6'
  description: 'Dependency updates (Renovate)'

- name: 'devcontainer'
  color: '1d76db'
  description: 'DevContainer related issues'
