---
# Security Alert Exceptions Configuration
# This file defines CVEs and patterns that should be auto-dismissed
# Edit this file to customize alert management behavior

# Configuration version (for future compatibility)
version: 1

# Global settings
settings:
  # Maximum age in days before alerts are dismissed as stale
  max_alert_age_days: 90

  # Default dismissal reason for stale alerts
  default_stale_reason: "won't fix"

  # Whether to add comments when dismissing
  add_comments: true

# Known false positives
# These will be dismissed automatically with reason "false positive"
false_positives:
  # Example: CVE that doesn't apply to our use case
  # - cve: "CVE-2024-XXXXX"
  #   reason: "We don't use the affected feature"
  #   comment: "This CVE affects the XYZ module which we have disabled."

# Accepted risks
# These will be dismissed with reason "used in tests"
accepted_risks:
  # Go stdlib CVEs in vendor binaries (age, sops, terragrunt, terraform, tflint)
  # These are pre-compiled binaries from upstream that we don't control
  # Impact: LOW - Development environment only, limited attack surface
  # Review: Quarterly or when upstream releases updates
  go_stdlib_vendor_binaries:
    description: "Go stdlib CVEs in vendored binaries we don't compile"
    rationale: "Development environment only. Binaries downloaded from upstream vendors. Limited attack surface (SSH server CVEs don't apply, DoS requires malicious input)."
    review_frequency: "Quarterly"
    affected_binaries:
      - "usr/local/bin/age"
      - "usr/local/bin/age-keygen"
      - "usr/local/bin/sops"
      - "usr/local/bin/terragrunt"
      - "usr/local/bin/terraform"
      - "usr/local/bin/tflint"
    cves:
      # golang.org/x/crypto CVEs
      - "CVE-2025-58181"  # SSH GSSAPI authentication validation (MEDIUM)
      - "CVE-2025-47914"  # SSH Agent message size validation (MEDIUM)
      # net/mail, net/textproto CVEs
      - "CVE-2025-61725"  # net/mail ParseAddress CPU exhaustion (MEDIUM)
      - "CVE-2025-61724"  # net/textproto ReadResponse CPU exhaustion (MEDIUM)
      # encoding CVEs
      - "CVE-2025-61723"  # encoding/pem quadratic complexity (MEDIUM)
      - "CVE-2025-58185"  # encoding/asn1 unbounded memory exhaustion (HIGH)
      # crypto CVEs
      - "CVE-2025-58189"  # crypto/tls ALPN protocol (HIGH)
      - "CVE-2025-58188"  # crypto/x509 DSA signature panic (HIGH)
      - "CVE-2025-58187"  # crypto/x509 name constraint checking panic (HIGH)
      # net/http CVEs
      - "CVE-2025-58186"  # net/http cookie header DoS (HIGH)
      # archive/tar CVEs
      - "CVE-2025-58183"  # archive/tar unbounded allocation (HIGH)
      # net/url CVEs
      - "CVE-2025-47912"  # net/url IPv6 validation (MEDIUM)

# CVE exceptions with custom logic
exceptions:
  # Example: Podman vulnerabilities in rootless mode
  # - cves:
  #     - "CVE-2024-1753"
  #     - "CVE-2024-9407"
  #   condition: "rootless"
  #   reason: "won't fix"
  #   comment: "These CVEs only affect rootful mode. We use Podman in rootless mode exclusively."

# Age-based dismissal rules
age_based_dismissal:
  # Dismiss low severity alerts after 30 days
  - severity: "note"
    days: 30
    reason: "won't fix"
    comment: "Low severity alert auto-dismissed after 30 days."

  # Dismiss medium severity after 90 days
  - severity: "warning"
    days: 90
    reason: "won't fix"
    comment: "Medium severity alert auto-dismissed after 90 days with no fix available."

# Tool-specific rules
tool_rules:
  trivy:
    # Ignore unfixed vulnerabilities (Trivy already does this, but documented here)
    ignore_unfixed: true

    # Custom dismissal patterns
    patterns:
      # Example: Dismiss Go stdlib vulnerabilities in copied binaries
      # - location_pattern: "usr/local/bin/*"
      #   package_pattern: "golang.org/x/*"
      #   days: 60
      #   reason: "used in tests"
      #   comment: "Go stdlib vulnerability in third-party binary. Monitoring upstream."

# Notes and documentation
notes: |
  This configuration file helps maintain a clean security alert dashboard while
  ensuring critical issues are addressed.

  Guidelines:
  1. Only dismiss alerts after investigation
  2. Document the reason for each exception
  3. Review this file quarterly
  4. Keep high-severity alerts visible until fixed

  Review schedule:
  - Weekly: Check new alerts
  - Monthly: Review dismissed alerts
  - Quarterly: Update this configuration

  Last reviewed: 2025-12-02
  Next review: 2026-03-02
