# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: 60%
        threshold: 2%
        if_ci_failed: error
    patch:
      default:
        target: 60%
        threshold: 5%
        if_ci_failed: error
    changes:
      default:
        if_ci_failed: error

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "tests/**"
  - "**/__pycache__/**"
  - "**/test_*.py"
  - "docs/**"
  - "examples/**"
  - "scripts/bootstrap-windows.ps1"

flags:
  python:
    paths:
      - roles/
      - playbooks/
      - scripts/
    carryforward: true
  golang:
    paths:
      - "**/*.go"
    carryforward: true
