name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees:
  - malpanez

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us fix it.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what went wrong
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Open devcontainer
        2. Run command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: It should...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Instead it...
    validations:
      required: true

  - type: dropdown
    id: stack
    attributes:
      label: Which DevContainer Stack?
      options:
        - Terraform (.devcontainer)
        - Ansible (devcontainers/ansible)
        - Golang (devcontainers/golang)
        - LaTeX (devcontainers/latex)
        - Base (devcontainers/base)
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version/Tag
      description: Which version are you using? (latest, specific tag, commit SHA)
      placeholder: "latest / v1.2.3 / abc123"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Host Operating System
      options:
        - macOS
        - Windows (WSL2)
        - Linux
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please copy and paste any relevant log output
      render: shell
      placeholder: Paste logs here

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided all requested information
          required: true
        - label: I am using the latest version
          required: false
