---
- name: Converge vscode_config role
  hosts: all
  become: true
  vars:
    test_devcontainer_user: vscode
    test_workspace_dir: /workspace
  pre_tasks:
    - name: Ensure devcontainer user exists
      ansible.builtin.user:
        name: "{{ test_devcontainer_user }}"
        shell: /bin/bash
        state: present

    - name: Ensure workspace directory exists
      ansible.builtin.file:
        path: "{{ test_workspace_dir }}"
        state: directory
        owner: "{{ test_devcontainer_user }}"
        group: "{{ test_devcontainer_user }}"
        mode: '0755'

  roles:
    - role: vscode_config
      vars:
        vscode_config_devcontainer_user: "{{ test_devcontainer_user }}"
        vscode_config_workspace_dir: "{{ test_workspace_dir }}"
