---
dependency:
  name: galaxy
  options:
    requirements_file: ../../requirements.yml

driver:
  name: docker

platforms:
  - name: ${TEST_DISTRO:-debian12}
    image: ${TEST_IMAGE:-geerlingguy/docker-debian12-ansible:latest}
    privileged: true
    override_command: true
    command: sleep infinity
    environment:
      ANSIBLE_FORCE_COLOR: "true"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles:~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles
    ANSIBLE_COLLECTIONS_PATH: ../../collections:~/.ansible/collections:/usr/share/ansible/collections
    ANSIBLE_REMOTE_TMP: /tmp/ansible-remote
  playbooks:
    converge: converge.yml
    verify: verify.yml

scenario:
  test_sequence:
    - converge
    - verify
    - destroy
